<?php
$_product = $block->getProduct();
$subStatus = $_product->getData('subscription_status');
               $sub_name = $_product->getData('subscription_name');
               $subscription = $block->getSubscription();
        if ($this->getSubscribed()) :
            ?>
            <span><?= $block->escapeHtml(__('Already Subscribed')) ?></span>
            <?php
        elseif (!empty($subscription) )  :?>
        <p><?php //echo  json_encode($_product->getData('type'))  ?></p>
        <div class="box-tocart">
            <div class="fieldset">
                <div class="field qty">
                    <div class="control text-center">
                        <!--<label class="label">
                            <input type="radio" name="subscription" value="0" title="No Subscription"
                            class="input-radio" data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>" />
                            <span><?= $block->escapeHtml(__('No Subscription')) ?></span>
                        </label>-->
                        <label class="label">
                            <input type="checkbox" name="subscription" value="1" title="Subscription"
                            class="input-radio" data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>" />
                            <span><?= $block->escapeHtml(__('Subscribe Now')) ?></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="subscription">
                <div class="fieldset">
                    <div class="field">
                        <label class="label" for="frequency"><span><?= $block->escapeHtml(__('Frequency')) ?></span></label>
                        <div class="control">
                            <select name='frequency' class='form-control'>
                                <?php
                                foreach ($subscription['type'] as $key => $value) { ?>
                                    <option value="<?= $key ?>"><?= $value ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label" for="qty"><span><?= $block->escapeHtml(__('Subscription Start Date')) ?></span></label>
                        <div class="control">
                            <input type="date" name="startdate" id="eventdate" placeholder="Event Date" value="" class="input-text"  data-validate="{required:true, 'validate-date':true}" >
                        </div>
                    </div>
                    <div class="field">
                        <label class="label" for="qty"><span><?= $block->escapeHtml(__('Subscription End By')) ?></span></label>
                        <div class="control">
                            <label class="label">
                                <input type="radio" name="subscription_end_by" value="Date" title="Subscription" class="input-radio"  />
                                <span><?= $block->escapeHtml(__('End By Date')) ?></span>
                            </label>
                            <label class="label">
                                <input type="radio" name="subscription_end_by" value="Cycle" title="Subscription" class="input-radio" />
                                <span><?= $block->escapeHtml(__('End By Cycle')) ?></span>
                            </label>
                            <label class="label">
                                <input type="radio" name="subscription_end_by" value="Until" title="Subscription" class="input-radio" />
                                <span><?= $block->escapeHtml(__('Until You Cancel')) ?></span>
                            </label>
                        </div>
                    </div>
                    <div class="field">
                        <div class="end_by_date">
                            <label class="label" for="enddate"><span><?= $block->escapeHtml(__('Select End Date')) ?></span></label>
                            <input type="date" name="enddate">
                        </div>
                        <div class="end_by_cycle">
                            <label class="label" for="orders"><span><?= $block->escapeHtml(__('No of Orders')) ?></span></label>
                            <input type="number" name="orders" id="orders" value="1" class="input-text" />
                        </div>
                    </div>
                    <?php if ($subscription['discount_status']) {?>
                    <div class="field">
                        <div class="discount_type">
                            <label class="label" for="type">
                                <span><?= $block->escapeHtml(__('Discount Type :')) ?><b>
                                <?=$subscription['discount_type']?></b></span></label>

                        </div>
                        <div class="discout_value">
                            <label class="label" for="value">
                                <span><?= $block->escapeHtml(__('Discount Value :')) ?>
                            <?=$subscription['discount_value']?></span></label>
                            
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <?php endif;?>



<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script>
require(['jquery', "mage/calendar"], function($){
 

    $(document).ready(function(){

        $('div.subscription').hide();
        $('div.end_by_date').hide();
        $('div.end_by_cycle').hide();
        var dtToday = new Date();
        var month = dtToday.getMonth() + 1;
        var day = dtToday.getDate()+1;
        var year = dtToday.getFullYear();
        if(month < 10)
            month = '0' + month.toString();
        if(day < 10)
            day = '0' + day.toString();
            var today = year + '-' + month + '-' + day;    
            
             $("input[name=startdate]").attr('min', today);
            $("input[name=enddate]").val(today);
            $("input[name=enddate]").attr('min', today);
        $('input[name="subscription"]').on('click',function(){
            if($(this).prop('checked') == true)
                $('div.subscription').show();
            else
                $('div.subscription').hide();
        });
        $('input[name="subscription_end_by"]').on('click',function(){
            if($(this).val() == 'Date'){
                $('div.end_by_date').show();
                $('div.end_by_cycle').hide();
            }else if($(this).val() == 'Cycle'){
                $('div.end_by_date').hide();
                $('div.end_by_cycle').show();
            }
            else{
                $('div.end_by_date').hide();
                $('div.end_by_cycle').hide();
            }
        });
    });
});
</script>